export const INITIAL_STATE = {
  avgCostPerLead: 280,
  totalDailyLeads: 200,
  presales: { capacity: 180, leadRate: 0.2, salary: 4500 },
  insalesSalary: 5000,
  promoLaborCost: 40000,
  management: { topManagers: 2, topSalary: 15000, centerSalary: 11000 },
  costRatio: { wuchuang: 3, geren: 2, sifaManualCost: null },
  categories: {
    wuchuang: {
      name: "无创",
      leadRatio: 0.2,
      convRate: 0.3,
      unitPrice: 2500,
      capacity: 7,
      centerManagers: 1,
      dealCost: 600,
      varCostRate: 0.05,
      processCost: 230,
    },
    geren: {
      name: "个人",
      leadRatio: 0.6,
      convRate: 0.26,
      unitPrice: 1500,
      capacity: 12,
      centerManagers: 3,
      dealCost: 345,
      varCostRate: 0.05,
      processCost: 75,
    },
    sifa: {
      name: "司法",
      leadRatio: 0.2,
      convRate: 0.26,
      unitPrice: 2500,
      capacity: 9,
      centerManagers: 1,
      sifaCostRate: 0.6,
      varCostRate: 0.05,
      processCost: 0,
    },
  },
};
